version: "3.8"

services:

  db:
    build:
      context: ./db

    image: ${COMPOSE_PROJECT_NAME}-db:trial

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - app-net

    labels:
      owner: "${OWNER}"

  backend:
    build:
      context: ./backend

    image: ${COMPOSE_PROJECT_NAME}-backend:trial

    expose:
      - "5000"

    restart: always

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shopdb

    networks:
      - app-net

    labels:
      owner: "${OWNER}"

  web:
    build:
      context: ./web

    image: ${COMPOSE_PROJECT_NAME}-web:trial
    
    restart: always

    depends_on:
      - backend

    networks:
      - app-net

    labels:
      owner: "${OWNER}"

networks:

  app-net:
    name: ${COMPOSE_PROJECT_NAME}_app-net
    driver: bridge

volumes:

  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data