version: "3.8"

services:
  db:
    # Sử dụng biến để nhận tên Image gọn gàng từ code C#
    image: giahieu33271/shop-db:1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      dbtype: "mysql"
      service: "${SERVICE}"

  backend:
    # Sử dụng biến IMG_BACKEND
    image: giahieu33271/shop-backend:1.0
    expose:
      - "5000"
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shopdb
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"

  web:
    # Sử dụng biến IMG_WEB
    image: giahieu33271/shop-web:1.0
    restart: always
    depends_on:
      - backend
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"

networks:
  app-net:
    # name linh hoạt theo COMPOSE_PROJECT_NAME (app)
    name: ${COMPOSE_PROJECT_NAME}_app-net
    driver: bridge

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data