version: "3.8"

services:
  db:
    image: giahieu33271/shop-db:1.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - app-net

    labels:
      owner: "${OWNER}"

  backend:
    image: giahieu33271/shop-backend:1.0

    restart: always

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shopdb

    networks:
      - app-net

    labels:
      owner: "${OWNER}"

  web:
    image: giahieu33271/shop-web:1.0

    restart: always

    depends_on:
      - backend

    networks:
      - app-net

    labels:
      owner: "${OWNER}"

networks:
  app-net:
    name: ${COMPOSE_PROJECT_NAME}_app-net
    driver: bridge

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
