services:
  db:
    # Sử dụng biến môi trường để nhận tên Image động từ code C#
    image: ${IMG_DB}
    restart: always
    deploy:
      replicas: 1
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"
      dbtype: "mysql"

  backend:
    # Sử dụng biến môi trường động
    image: ${IMG_BACKEND}
    restart: always
    deploy:
      replicas: 2 # Mặc định khởi tạo 2 con, thích scale bằng CLI thì scale
    expose:
      - "5000"   # Mở cổng nội bộ trong app-net để dịch vụ khác gọi vào
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shopdb
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"

  web:
    # Sử dụng biến môi trường động
    image: ${IMG_WEB}
    restart: always
    deploy:
      replicas: 2 # Mặc định khởi tạo 2 con
    expose:
      - "80"     # Chỉ mở nội bộ trong mạng app-net cho LB Container gọi vào
    depends_on:
      - backend
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"

networks:
  app-net:
    # Tên mạng logic ăn theo tên project để biệt lập cụm container của từng app
    name: ${COMPOSE_PROJECT_NAME}_app-net
    driver: bridge

volumes:
  db_data:
    # Tên volume lưu data của DB để tránh bị mất dữ liệu khi restart/up lại container
    name: ${COMPOSE_PROJECT_NAME}_db_data