services:
  db:
    build: ./db
    image: ${IMG_DB}
    restart: always
    deploy:
      replicas: 1
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"
      dbtype: "mysql"
      type: "db"

  backend:
    build: ./backend
    image: ${IMG_BACKEND}
    restart: always
    deploy:
      replicas: 1
    expose:
      - "5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shopdb
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"
      type: "backend"

  web:
    build: ./web
    image: ${IMG_WEB}
    restart: always
    deploy:
      replicas: 1
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-net
    labels:
      owner: "${OWNER}"
      service: "${SERVICE}"
      type: "frontend"

networks:
  app-net:
    name: ${COMPOSE_PROJECT_NAME}_app-net
    driver: bridge

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data